{ config
, pkgs
, lib
, inputs
, ...
}:
let
  # Get the ghostty config generated by home-manager's programs.ghostty.settings
  ghosttySettings = config.programs.ghostty.settings;
  
  # Create a script that merges config-dankcolors with settings  
  mergedConfig = pkgs.writeShellScript "merge-ghostty-config" ''
    dankcolors_file="$HOME/.config/ghostty/config-dankcolors"
    config_file="$HOME/.config/ghostty/config"
    temp_file="$config_file.tmp"
    
    # Start with the generated config from home-manager
    cat > "$temp_file" << 'HM_CONFIG'
${lib.optionalString (ghosttySettings != {}) 
  (lib.generators.toKeyValue 
    { mkKeyValue = lib.generators.mkKeyValueDefault {} " = "; }
    ghosttySettings)}
HM_CONFIG

    # Append dankcolors if it exists
    if [ -f "$dankcolors_file" ]; then
      echo "" >> "$temp_file"
      echo "# Colors from dankMaterialShell (dankcolors)" >> "$temp_file"
      cat "$dankcolors_file" >> "$temp_file"
    fi
    
    # Move the temp file to the final location
    mv "$temp_file" "$config_file"
  '';
in
{
  programs.ghostty = {
    enable = true;
    package = inputs.ghostty.packages.${pkgs.system}.default;
    enableFishIntegration = true;
    installVimSyntax = true;
    
    settings = {
      # Add your additional ghostty configuration here
      # Colors from config-dankcolors will be appended automatically
    };
  };

  # Disable the default config file generation since we'll create it via activation
  xdg.configFile."ghostty/config".enable = false;

  # Merge config-dankcolors with home-manager settings during activation
  home.activation.mergeGhosttyConfig =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD ${mergedConfig}
    '';

  # Enable ghostty systemd service on activation
  home.activation.enableGhosttyService =
    lib.hm.dag.entryAfter [ "reloadSystemd" ] ''
      $DRY_RUN_CMD ${pkgs.systemd}/bin/systemctl --user enable app-com.mitchellh.ghostty.service || true
    '';

  # Create desktop entry for drop-down terminal to use Ghostty's icon
  xdg.dataFile."applications/com.kc.dropterm.desktop".text = ''
    [Desktop Entry]
    Type=Application
    Name=Ghostty Drop-down Terminal
    Comment=Drop-down terminal using Ghostty
    Icon=com.mitchellh.ghostty
    Exec=${pkgs.ghostty}/bin/ghostty --class=com.kc.dropterm
    Terminal=false
    Categories=System;TerminalEmulator;
    StartupWMClass=com.kc.dropterm
    NoDisplay=true
  '';
}
