name: CI

on:
  push:
    branches:
      - master
    paths:
      - '**.nix'
      - '**.age'
      - 'flake.lock'

  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      # Prevent concurrent builds to avoid disk space issues
      max-parallel: 1
      matrix:
        hostname:
          - edge
          - pangolin
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@v9

      - name: Cache in Flakehub Cache
        uses: DeterminateSystems/flakehub-cache-action@main    
        
      - name: Apply Nix binary cache config
        run: |
           sudo tee -a /etc/nix/nix.custom.conf > /dev/null <<EOF
           substituters = https://cosmic.cachix.org/ https://cache.nixos.org/
           trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=  
           EOF
           
      - name: "Build ${{ matrix.hostname }}"
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel

