name: "Publish every git push to FlakeHub"
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@main"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "private"
          name: "kcalvelli/nixos_config"  
          rolling: "true"   